version: '3.11.4'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
    # 이설정으로 postgres에서 만들고
    # 장고에서 사진 env로 만든다 생각
    env_file:
      - ./.env.postgres
    # 나중에 db내용 보고싶을떄 열어두는 포트
    ports:
      - "5432:5432"

volumes:
  # 선언해줌
  postgres_db: