# Generated by Django 4.2.5 on 2024-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslog',
            name='game_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chesslog',
            name='move_log',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chesslog',
            name='turn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
