# Generated by Django 5.0.1 on 2024-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_alter_chesslog_board_state_alter_chesslog_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslog',
            name='turn',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
