# Generated by Django 5.0.1 on 2024-02-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_alter_chesslog_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesslog',
            name='game_state',
        ),
        migrations.AddField(
            model_name='chesslog',
            name='player_1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chesslog',
            name='player_2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chesslog',
            name='result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw')], max_length=10, null=True),
        ),
    ]
