# Generated by Django 5.0.1 on 2024-02-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_remove_chesslog_game_state_chesslog_player_1_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslog',
            name='player_1_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chesslog',
            name='player_2_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
