# Generated by Django 4.2.5 on 2024-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('rank', models.SmallIntegerField(default=1000)),
                ('win', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
